# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Run tests for Report Portal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  run-tests-on-linux:
    name: Run tests on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --no-parallel --no-daemon --console=plain -DenvName=local -Dselenide.headless=true
    - name: Report
      uses: turing85/publish-report@v1
      if: always()
      with:
        report-name: Report Portal Tests
        report-path: build/test-results/test/TEST-*.xml
        report-reporter: java-junit
        report-fail-on-error: true
        recreate-comment: true
